name: ci

on:
  push:
    branches:
    - "*"  # run for branches
    tags:
    - "*"  # run for tags
  pull_request:
    branches:
    - "*"  # run for branches
    tags:
    - "*"  # run for tags

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      GROUP: khulnasoft
      COMMIT: ${{ github.sha }}
      REPO: demo-app
      KHULNASOFT_CONSOLE_URL: 1.1.1.1
    steps:
    - uses: actions/checkout@v2

    # Build docker image for service
    - name: Build docker image
      uses: docker/build-push-action@v1
      with:
        push: false
        repository: ${{ env.GROUP }}/${{ env.REPO }}
        tag_with_ref: true
        tag_with_sha: true
        tags: ${{ github.sha }}

    # Run Deepfence Vulnerability Mapper to check for vulnerabilities in image
    - name: Run Deepfence Vulnerability Mapper
      env:
        KHULNASOFT_CONSOLE_URL: ${{ env.KHULNASOFT_CONSOLE_URL }}
        KHULNASOFT_KEY: ${{ env.GROUP }}
        FULL_IMAGE_NAME: ${{ env.GROUP }}/${{ env.REPO }}:${{ github.sha }}
        FAIL_CVE_COUNT: 100 # Fail build if number of vulnerabilities found is >= this number. Set -1 to pass regardless of vulnerabilities.
        FAIL_CVE_SCORE: 8 # Fail build if cumulative CVE score is >= this value. Set -1 to pass regardless of cve score.
      run: |
        mkdir khulnasoft_docker
        docker_config_path="$(pwd)/khulnasoft_docker"
        docker_creds=$(echo -n "${{ secrets.DOCKER_USERNAME }}:${{ secrets.DOCKER_TOKEN }}" | base64)
        echo "{\"auths\":{\"https://index.docker.io/v1/\":{\"auth\":\"$docker_creds\"}}}" > "$docker_config_path/config.json"
        docker --config "$docker_config_path" pull khulnasoft/khulnasoft_vulnerability_mapper:3.7.3
        rm -rf khulnasoft_docker
        docker run --rm --net=host --privileged=true -v /var/run/docker.sock:/var/run/docker.sock:rw khulnasoft/khulnasoft_vulnerability_mapper:3.7.3 -mgmt-console-url=$KHULNASOFT_CONSOLE_URL -khulnasoft-key="$KHULNASOFT_KEY" -image-name="$FULL_IMAGE_NAME" -fail-cve-count=$FAIL_CVE_COUNT -fail-cve-score=$FAIL_CVE_SCORE -scan-type="base,java,python,ruby,php,nodejs,js,dotnet"

    # Push to dockerhub
    - name: Push to Docker Hub
      uses: docker/build-push-action@v1
      if: startsWith(github.ref, 'refs/tags/v') || github.ref == 'refs/heads/master'
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_TOKEN }}
        repository: ${{ env.GROUP }}/${{ env.REPO }}
        tag_with_ref: true
        tag_with_sha: true
